USE [master]
GO
/****** Object:  Database [LBD]    Script Date: 05/06/2020 09:13:58 a. m. ******/
CREATE DATABASE [LBD]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LBD', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\LBD.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'LBD_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\LBD_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [LBD] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LBD].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [LBD] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [LBD] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [LBD] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [LBD] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [LBD] SET ARITHABORT OFF 
GO
ALTER DATABASE [LBD] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [LBD] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [LBD] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [LBD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [LBD] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [LBD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [LBD] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [LBD] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [LBD] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [LBD] SET  ENABLE_BROKER 
GO
ALTER DATABASE [LBD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [LBD] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [LBD] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [LBD] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [LBD] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [LBD] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [LBD] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [LBD] SET RECOVERY FULL 
GO
ALTER DATABASE [LBD] SET  MULTI_USER 
GO
ALTER DATABASE [LBD] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [LBD] SET DB_CHAINING OFF 
GO
ALTER DATABASE [LBD] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [LBD] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [LBD] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'LBD', N'ON'
GO
ALTER DATABASE [LBD] SET QUERY_STORE = OFF
GO
USE [LBD]
GO

-- PRACTICA 5 --

-- 5 simple selects with where clause:

-- 1
SELECT ID_Cliente, NombreCompleto FROM Clientes WHERE Edad BETWEEN 24 AND 30
-- 2
SELECT RFC, RazonSocial FROM Proveedores WHERE Colonia IN ('GUADALUPE', 'CALETA')
-- 3
SELECT Nombre, DireccionAlmacen FROM Almacenes WHERE Estado <> 'Jalisco'
-- 4
SELECT Nombre, Costo FROM Producto WHERE Costo >= 550
-- 5
SELECT ID_Pedido, ID_Cliente FROM Pedidos WHERE FechaPedido = '2020-01-25'

-- 5 selects with Group by clause:

--1
SELECT Categoria, COUNT(ID_Producto) AS TotalProductos
FROM Producto
GROUP BY Categoria;
-- 2
SELECT Estado, COUNT(ID_Almacen) AS TotalAlamcenes
FROM Almacenes
GROUP BY Estado;
-- 3
SELECT ID_Proveedor, COUNT(ID_Producto) AS TotalVentas
FROM Pedidos
GROUP BY ID_Proveedor;
 -- 4
SELECT Edad, COUNT(ID_Cliente) AS TotalEdad
FROM Clientes
GROUP BY Edad;
-- 5
SELECT Colonia,  COUNT(ID_Proveedor) AS TotalProveedores
FROM Proveedores
GROUP BY Colonia;

-- 5 selects using *aggregate funtions:

-- 1
SELECT COUNT(*) AS NumeroClientes 
FROM Clientes;  
-- 2
SELECT AVG(Edad) AS PromedioEdad 
FROM Clientes;  
-- 2
SELECT MAX(Costo) AS CostoMaximo 
FROM Producto;
-- 4
SELECT SUM(ID_Pedido) AS TotalPedidos 
FROM Pedidos;
-- 5
SELECT SUM(ID_Pedido) AS TotalPedidos 
FROM Pedidos;

-- 5 select with Having clause:

-- 1
SELECT COUNT(ID_Cliente) AS ClientesTotales_Mayores23, Edad
FROM Clientes
GROUP BY Edad
HAVING Edad > 23
-- 2
SELECT COUNT(ID_Proveedor) AS TotaProveedores_NuevoLeon, Estado
FROM Proveedores
GROUP BY Estado
HAVING Estado = 'Nuevo Leon'
-- 3
SELECT COUNT(ID_Pedido) AS PedidosTotalesDia_2020, FechaPedido
FROM Pedidos
GROUP BY FechaPedido
HAVING FechaPedido BETWEEN '2020-01-01' AND '2020-12-31'
-- 4
SELECT COUNT(ID_Producto) AS Total_ProductosNutricion, Categoria
FROM Producto
GROUP BY Categoria
HAVING Categoria = 'Nutricion'
-- 5
SELECT Colonia, COUNT(ID_Almacen) AS TotalAlmacenes
FROM Almacenes
GROUP BY Colonia
HAVING Colonia = 'San Patricio'

-- 5 Select with Top:

-- 1
SELECT TOP 5 * FROM Clientes;
-- 2
SELECT TOP 50 PERCENT * FROM Proveedores 
WHERE CodigoPostal BETWEEN 66000 AND 99000
-- 3
SELECT TOP 3 * FROM Producto
WHERE Costo < 300
-- 4
SELECT TOP 3 * FROM Almacenes
WHERE Estado = 'Ciudad de Mexico';
-- 5
SELECT TOP 20 PERCENT * FROM Pedidos 
WHERE ID_Proveedor = 4
